name=WiFiController
version=1.0.0
author=Leandro Tavares da Silva
maintainer=Leandro Tavares da Silva
sentence=Gerenciamento avançado de WiFi para ESP8266 e ESP32.
paragraph=Biblioteca que fornece STA, Access Point, Captive Portal, mDNS automático, fallback AP e callbacks de eventos WiFi.
category=Communication
url=https://github.com/ltavasilva/WiFiController
architectures=esp8266,esp32