name: Compile Examples

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32dev
          - esp8266:esp8266:nodemcuv2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install cores
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32
        arduino-cli core install esp8266:esp8266

    - name: Install required libraries
      run: |
        arduino-cli lib install "DNSServer"
        arduino-cli lib install "ESP8266WebServer"
        arduino-cli lib install "ESP32"   # se necessário
        # Adicione qualquer outra biblioteca usada nos exemplos

    - name: Compile all examples
      run: |
        for f in examples/*/*.ino; do
          arduino-cli compile --fqbn ${{ matrix.fqbn }} "$f"
        done
