name: Arduino Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          # Esta flag avisa que você está atualizando uma biblioteca existente
          flags: --library-manager update
